import { GraphData } from './types';
import { generateLinks } from './graphUtils';

const nodes = [
  {
    id: 'crash-course',
    topic: 'A crash course in \"crash course',
    title: 'A crash course in \"crash course',
    descriptor: 'The Too-Often-Untold Story of The Totally Uncloneable Hank Green',
    imageUrl: 'https://cdn.prod.website-files.com/66b0cbf53f3798cc2ace2b42/66c35b57bfb182b3b38b3727_66c35791cdd6ab918c5e69ed_Art_3_Splash.avif',
    author: 'nick-gaudio',
    issue: 'com-1-august-2024',
    tags: 'youtube; creators; opinion',
    type: 'article',
    x: 0,
    y: 0,
    z: 0
  },
  {
    id: 'like-worth',
    topic: "What's a like on Instagram 'worth' in 2024?",
    title: "What's a like on Instagram 'worth' in 2024?",
    descriptor: "Actually… More Than You'd Think!",
    imageUrl: 'https://cdn.prod.website-files.com/66b0cbf53f3798cc2ace2b42/66c35b656b4ad8437c28b691_66c357918e37552c6623c6e7_Art_1_Splash.avif',
    author: 'nick-gaudio',
    issue: 'com-1-august-2024',
    tags: 'instagram; influencers; marketers; creators',
    type: 'article',
    x: 50,
    y: 0,
    z: 0
  },
  {
    id: 'speed-sells',
    topic: "Speed sells: Why it's important to respond lickety-split",
    title: "Speed sells: Why it's important to respond lickety-split",
    descriptor: "",
    imageUrl: 'https://cdn.prod.website-files.com/66b0cbf53f3798cc2ace2b42/66c35b883ba1d3f499457b0c_66c357b16fde1d8a9b5a02c5_Art_2_Splash.avif',
    author: 'nick-gaudio',
    issue: 'com-1-august-2024',
    tags: 'marketers; creators; influencers',
    type: 'article',
    x: -50,
    y: 0,
    z: 0
  },
  {
    id: 'survey-creators-psychology',
    topic: 'Survey: Сreators feeling stress, stress, and careful curations',
    title: 'Survey: Сreators feeling stress, stress, and careful curations',
    descriptor: '',
    imageUrl: 'https://cdn.prod.website-files.com/66b0cbf53f3798cc2ace2b42/66f1629c34ce3b4fd720b973_Art_5_Feature.avif',
    author: 'dustin-dooling',
    issue: 'com-2-sep-2024',
    tags: 'creators; survey; trends',
    type: 'article',
    x: 0,
    y: 50,
    z: 0
  },
  {
    id: 'creators-in-the-headlights',
    topic: 'Creators in the Headlights: When Big Media Shifts Gears',
    title: 'Creators in the Headlights: When Big Media Shifts Gears',
    descriptor: '',
    imageUrl: 'https://cdn.prod.website-files.com/66b0cbf53f3798cc2ace2b42/66f162b83bf5eee0c536fc52_Art_6_Feature.avif',
    author: 'robert-hilliard',
    issue: 'com-2-sep-2024',
    tags: 'creators; youtube; news',
    type: 'article',
    x: 50,
    y: 50,
    z: 0
  },
  {
    id: 'will-post-for-food',
    topic: 'Will Post for Food',
    title: 'Will Post for Food',
    descriptor: '',
    imageUrl: 'https://cdn.prod.website-files.com/66b0cbf53f3798cc2ace2b42/66f186f8ea579be24ac2dff4_Art_4_Feature_1.avif',
    author: 'nick-gaudio',
    issue: 'com-2-sep-2024',
    tags: 'opinion; creators; instagram; trends',
    type: 'article',
    x: -50,
    y: 50,
    z: 0
  },
  {
    id: 'robots-red-lace',
    topic: 'Robots & Red Lace',
    title: 'Robots & Red Lace',
    descriptor: "How OnlyFans Creators Are Using AI for 'Intimacy at Scale'",
    imageUrl: 'https://cdn.prod.website-files.com/66b0cbf53f3798cc2ace2b42/671fa6b106217cf3b311fe44_Feature_A2-3.avif',
    author: 'nick-gaudio',
    issue: 'com-3-edition',
    tags: 'instagram; influencers; creators; bot-builders',
    type: 'article',
    x: 0,
    y: -50,
    z: 0
  },
  {
    id: 'mr-least',
    topic: 'From Mr. Beast to Mr. Least?',
    title: 'From Mr. Beast to Mr. Least?',
    descriptor: 'Lessons from creator to CEO (and the collateral damage along the way)',
    imageUrl: 'https://cdn.prod.website-files.com/66b0cbf53f3798cc2ace2b42/671fa5604eacaedf503f2cd6_Feature_A2-2.avif',
    author: 'ashley-sava',
    issue: 'com-3-edition',
    tags: 'youtube; creators; influencers; news',
    type: 'article',
    x: 50,
    y: -50,
    z: 0
  },
  {
    id: 'parental-discretion-advised',
    topic: 'Parental Discretion (Still) Advised',
    title: 'Parental Discretion (Still) Advised',
    descriptor: "Going undercover with Instagram's new Teen Accounts",
    imageUrl: 'https://cdn.prod.website-files.com/66b0cbf53f3798cc2ace2b42/671fa6caa89e547b3bd93e0e_Feature_A3.avif',
    author: 'dustin-dooling',
    issue: 'com-3-edition',
    tags: 'instagram; news; marketers; influencers',
    type: 'article',
    x: -50,
    y: -50,
    z: 0
  },
  {
    id: 'email-doesnt-suck',
    topic: "It's 2024 and — Wait, Email Doesn't Suck?",
    title: "It's 2024 and — Wait, Email Doesn't Suck?",
    descriptor: 'Creators, fans, and the strikingly powerful sticking power of getting an email address.',
    imageUrl: 'https://cdn.prod.website-files.com/66b0cbf53f3798cc2ace2b42/671fa6e6883fde668bb72aea_Feature_A5-1.avif',
    author: 'nick-gaudio',
    issue: 'com-3-edition',
    tags: 'opinion; marketers; agencies',
    type: 'article',
    x: 25,
    y: 25,
    z: 25
  },
  {
    id: 'cardboard-pizza',
    topic: 'Cardboard Pizza: The Deadly Art of Losing Your Social Media Credibility',
    title: 'Cardboard Pizza: The Deadly Art of Losing Your Social Media Credibility',
    descriptor: '',
    imageUrl: 'https://cdn.prod.website-files.com/66b0cbf53f3798cc2ace2b42/671fa7127645f993bf2f0470_Feature_A2-4.avif',
    author: 'robert-hilliard',
    issue: 'com-3-edition',
    tags: 'influencers; opinion; trends',
    type: 'article',
    x: -25,
    y: 25,
    z: 25
  },
  {
    id: 'fur-ever-famous',
    topic: 'Fur-Ever Famous',
    title: 'Fur-Ever Famous',
    descriptor: 'When Internet Pets Never (Officially) Die',
    imageUrl: 'https://cdn.prod.website-files.com/66b0cbf53f3798cc2ace2b42/6745a6b288a0d4961d7ec2a9_4_Feature_A1.avif',
    author: 'robert-hilliard',
    issue: 'november-issue',
    tags: '',
    type: 'article',
    x: 25,
    y: -25,
    z: 25
  },
  {
    id: 'engagement-dread',
    topic: "Engagement Dread: It's Not Your Fault (But It Kinda Is?)",
    title: "Engagement Dread: It's Not Your Fault (But It Kinda Is?)",
    descriptor: '',
    imageUrl: 'https://cdn.prod.website-files.com/66b0cbf53f3798cc2ace2b42/6745a74615e706bbc37165f8_4_Feature_A5.avif',
    author: 'nick-gaudio',
    issue: 'november-issue',
    tags: '',
    type: 'article',
    x: -25,
    y: -25,
    z: 25
  },
  {
    id: 'still-posting',
    topic: 'Still Posting Post-Death',
    title: 'Still Posting Post-Death',
    descriptor: 'The future of social: Too many zombies, not enough brains',
    imageUrl: 'https://cdn.prod.website-files.com/66b0cbf53f3798cc2ace2b42/6746f84a23ad26938dddd3c8_Feature_A3.avif',
    author: 'dustin-dooling',
    issue: 'november-issue',
    tags: '',
    type: 'article',
    x: 25,
    y: 25,
    z: -25
  },
  {
    id: 'mercy-kill',
    topic: 'Mercy Kill Your Online Persona',
    title: 'Mercy Kill Your Online Persona',
    descriptor: 'A Step-by-Step Guide to Euthanizing Your Brand',
    imageUrl: 'https://cdn.prod.website-files.com/66b0cbf53f3798cc2ace2b42/6745a77d1aa6309002cd2f80_4_Feature_A4.avif',
    author: 'ashley-sava',
    issue: 'november-issue',
    tags: '',
    type: 'article',
    x: -25,
    y: 25,
    z: -25
  },
  {
    id: 'prove-youre-human',
    topic: "Prove You're Human",
    title: "Prove You're Human",
    descriptor: '',
    imageUrl: 'https://cdn.prod.website-files.com/66b0cbf53f3798cc2ace2b42/6745a7bfefbafc1c8e5fc26d_4_Feature_A2.avif',
    author: 'nick-gaudio',
    issue: 'november-issue',
    tags: '',
    type: 'article',
    x: 25,
    y: -25,
    z: -25
  },
  {
    id: 'creator-fortune',
    topic: "What's Your Creator Fortune?",
    title: "What's Your Creator Fortune?",
    descriptor: 'Understanding Your Tarot Card Future for 2025',
    imageUrl: 'https://cdn.prod.website-files.com/66b0cbf53f3798cc2ace2b42/676aea529861bfd54580285b_Feature_A3com5.jpg',
    author: 'ashley-sava',
    issue: 'december-issue',
    tags: 'quiz; creators; influencers',
    type: 'special_project',
    x: -25,
    y: -25,
    z: -25
  },
  {
    id: '2025-bingo',
    topic: "That's Not On My Bingo Card: 2025 edition",
    title: "That's Not On My Bingo Card: 2025 edition",
    descriptor: '2025 edition',
    imageUrl: 'https://cdn.prod.website-files.com/66b0cbf53f3798cc2ace2b42/676aea64f1ad8bf1a6a48f0e_Feature_A4com5.jpg',
    author: 'nick-gaudio',
    issue: 'december-issue',
    tags: '',
    type: 'special_project',
    x: 0,
    y: 0,
    z: 50
  },
  {
    id: 'parasocial-paradox',
    topic: 'The Parasocial Paradox',
    title: 'The Parasocial Paradox',
    descriptor: 'The Flipside of Instagram Fame',
    imageUrl: 'https://cdn.prod.website-files.com/66b0cbf53f3798cc2ace2b42/676aea780211dcaef8d6a5fd_Feature_A1com5.jpg',
    author: 'maria-valaikaite',
    issue: 'december-issue',
    tags: '',
    type: 'article',
    x: 0,
    y: 0,
    z: -50
  },
  {
    id: 'influencers-peaked',
    topic: 'Have Influencers Peaked?',
    title: 'Have Influencers Peaked?',
    descriptor: 'The Glittering Rise and the Quiet Plateau',
    imageUrl: 'https://cdn.prod.website-files.com/66b0cbf53f3798cc2ace2b42/676aead53185ee11f9b23527_Feature_A2com5-1.jpg',
    author: 'robert-hilliard',
    issue: 'december-issue',
    tags: '',
    type: 'article',
    x: 50,
    y: 0,
    z: 50
  },
  {
    id: 'reasons-to-expand',
    topic: 'Right & Wrong Reasons to Expand',
    title: 'Right & Wrong Reasons to Expand',
    descriptor: 'So you want to expand your social media empire? Let\'s talk about it.',
    imageUrl: 'https://cdn.prod.website-files.com/66b0cbf53f3798cc2ace2b42/6797639025be2e8f0c27d2f7_Feature_A1.jpg',
    author: 'ashley-sava',
    issue: 'january-issue',
    tags: '',
    type: 'article',
    x: -50,
    y: 0,
    z: 50
  }
];

export const newData: GraphData = {
  nodes,
  links: generateLinks(nodes)
}; 